#!/usr/bin/env bash
#
# author: keymon
# author: timmow
# author: dcarley
#
# source: https://dan.carley.co/blog/2016/03/31/when-did-submodule-include-commit-x/

set -euo pipefail

path=${1:?first parameter is submodule path}
commit=${2:?second parameter is commit-ish}

if ! [ -d "$path" ]; then
  echo "directory does not exist: ${path}"
  exit 1
fi

good_commits=$(git -C "${path}" rev-list "${commit}"^..HEAD)
if [ -z "${good_commits}" ]; then
  exit 1
fi

for parent_commit in $(git rev-list --reverse HEAD -- "${path}"); do
  sub_commit=$(git ls-tree -d "${parent_commit}" -- "${path}" | awk '{print $3}')
  if [ -z "${sub_commit}" ]; then
    continue
  fi
  if echo "${good_commits}" | grep -qw "${sub_commit}"; then
    echo "${parent_commit}"
    exit 0
  fi
done

exit 1
