#!/usr/bin/env bash
set -ueo pipefail

url="${1:?load_test url rps duration ; url is required}"
rps="${2:?load_test url rps duration ; rps is required}"
duration="${3:?load_test url rps ; duration is required ; eg 5m}"

headers=$(IFS=, eval 'echo "${@:4:$#-1}"')
request="GET $url\n$headers"

status_hist="code.hist.100+code.hist.200+code.hist.300+code.hist.400+code.hist.500"
latency="latency.p95+latency.p50+latency.p25"
bytes="bytes_in.sum+bytes_out.sum"

echo -e "$request"                               \
  | vegeta attack                                \
      -rate "$rps"                               \
      -duration "$duration"                      \
  | vegeta encode                                \
  | jaggr @count=rps                             \
      hist\[100,200,300,400,500\]:code           \
      p25,p50,p95:latency                        \
      sum:bytes_in                               \
      sum:bytes_out                              \
  | jplot rps "$status_hist" "$latency" "$bytes"
