#!/usr/bin/env bash

set -ueo pipefail
IFS=$'\n\t'

attempts=0

echo -n waiting for bridge100...
while ! ifconfig bridge100 >/dev/null 2>&1; do
  echo -n .

  attempts=$((attempts+1))
  sleep 1

  [ $attempts -gt 5 ] && (echo bailing ; exit 1)
done

echo
attempts=0

echo -n waiting for arp...
while ! arp -a -i bridge100  >/dev/null 2>&1; do
  echo -n .

  attempts=$((attempts+1))
  sleep 1

  [ $attempts -gt 5 ] && (echo bailing ; exit 1)
done

echo
attempts=0

addr="$(arp -a -i bridge100 \
  | grep -v incomplete \
  | grep -F 10. \
  | grep -vF .255 \
  | grep -Eo '10.211.[0-9]{1,3}.[0-9]{1,}' \
)"
ssh "$addr"
